# fly.toml app configuration file generated for sourcebot-staging on 2025-01-29T15:57:18-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sourcebot-staging'
primary_region = 'sea'

[build]
  image = 'sourcebot-staging'

[[mounts]]
  source = 'sourcebot_staging_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
